### ISSUE TITLE
sentinel fails on merge function on tags 

### ISSUE THREAD

**Issue by an-prog** [hashicorp/terraform-sentinel-policies#22]
while using the sentinel policy for mandatory tags on resources i am facing a challenge as the tags are using the merge function and will be generating on runtime on resource 
So there are default tags in a module and customs tags can be added in locals.tf and merge will then apply all tags in resource 
sentinel policy is not working on such scenario
please help

**Comment by hcrhall** [comment]
@an-prog I think it would be best if you post your question in [discuss.hashicorp.com](https://discuss.hashicorp.com/c/sentinel/25) as there is a broader audience.
