### ISSUE TITLE
The output of List format is incorrect when use plan.find_resources or tfplan.resource_changes

### ISSUE THREAD

**Issue by bonvoy88** [hashicorp/terraform-sentinel-policies#9]
### Issue Statement:

This issue occurs for GCP when we apply tfplan.resource_changes or plan.find_resources on "google_compute_firewall" where this resource contains a list of ports.

Input Data:

```python
"allow": [
					{
						"ports": [
							"80",
							"10-100",
							"1000-4000",
						],
						"protocol": "tcp",
					},
```
Output data:

```python
{"allow": [{"ports": ["80" "10-100" "1000-4000"], "protocol": "tcp"}]
```

i.e. the comma "," is missing between the list elements in the output.
[Link1 on Playground](https://play.sentinelproject.io/p/0DpzGekqx7t)

### Extract list elements, good example

Each list member is extracted correctly - because they are separated by a comma.

[List extract, good example](https://play.sentinelproject.io/p/jZ8-Qcj30I3)

### Extract list elements, error. 

**Implication** : Not able to extract list elements if list members are not separated by comma ","

[List extract, error](https://play.sentinelproject.io/p/5VU73suK06l)

### Questions

1. Why does the function remove the comma[s] from a list with multiple elements?
2. Is there some environment variables or some flags that can be set to include the comma[s] in the output?
3. What is the recommendation to extract each member of the list when they are not separated by comma[s]?
4. What function(s) can we use for list processing where elements are not complied to standard?

Any related advise or suggestion to overcome this feature is appreciated.

**Comment by bonvoy88** [comment]
Found answer from another support channel

**Comment by r-bennett** [comment]
@bonvoy88  what was the answer? Also running into this

**Comment by gr-raphlau** [comment]
For future reference, using `json.marshal` on a sentinel object returns correctly formatted json. https://developer.hashicorp.com/sentinel/docs/imports/json
